# Generated by Django 4.2.15 on 2024-08-15 00:34

from django.db import migrations, models
import youttify_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('youttify_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='youttifyuser',
            managers=[
                ('objects', youttify_auth.models.YouttifyUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='youttifyuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
